# --- USB & Console Routing ---
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_STACK_NEXT=n
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y
CONFIG_PRINTK=y

# --- Hardware ---
CONFIG_GPIO=y

# --- Bluetooth Core ---
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_NUS=y

# --- Forcing name on ble
CONFIG_BT_DEVICE_NAME="GaitSync"
CONFIG_BT_SETTINGS=n
CONFIG_BT_DEVICE_NAME_DYNAMIC=n

# -- voltage reading
CONFIG_ADC=y

# --- Bluetooth Memory Tweaks ---
CONFIG_BT_MAX_CONN=1
CONFIG_BT_ID_MAX=1

# Give the Bluetooth stack more internal buffer space
CONFIG_BT_BUF_ACL_TX_COUNT=10
CONFIG_BT_BUF_EVT_RX_COUNT=15
CONFIG_BT_L2CAP_TX_BUF_COUNT=10

# Increase the system heap so the stack doesn't run out of memory
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# Enabling Sensor API and Math library for IMU
CONFIG_SENSOR=y
CONFIG_NEWLIB_LIBC=y
CONFIG_FPU=y
CONFIG_I2C=y
# Power the IMU via the regulator API
CONFIG_REGULATOR=y
CONFIG_LSM6DSL=y

# Hardware Clock Fix to Prevent BLE lockups
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_500PPM=y