# --- Bluetooth Subsystem ---
CONFIG_BT=y

# --- NFC Core Libraries ---
CONFIG_NFC_T2T_NRFXLIB=y
CONFIG_NFC_NDEF=y
CONFIG_NFC_NDEF_MSG=y
CONFIG_NFC_NDEF_RECORD=y

# --- NFC Text Record ---
CONFIG_NFC_NDEF_TEXT_RECORD=y

# --- Low-Level Hardware Drivers ---
CONFIG_NRFX_NFCT=y
CONFIG_NFC_PLATFORM=y